services:
  tekkit2:
    image: kremity/tekkit2:1.2.6
    container_name: tekkit2
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MEMORY: 6G # Change this to your desired amount of RAM allocation, 6G is recommended
      TZ: Europe/Amsterdam # Change this to your desried timezone
    volumes:
      - /mnt/data/tekkit2:/tekkit2 # Change this to your desired host directory
    stdin_open: true
    tty: true
    networks:
      - tekkit-server

networks:
  tekkit-server:
    name: tekkit-server
